const data = [
    {
        id:0,
        url:"https://www.cnbctv18.com/market/stocks/stock-market-news-live-updates-nifty50-bse-sensex-hcl-tech-nestle-lt-tech-tata-elxsi-brent-crude-bitcoin-gold-price-13222162.htm",
        img:"https://images.cnbctv18.com/wp-content/uploads/2019/07/BSE-Sensex.jpg",
        time:"2022-04-21T12:17:49Z",
        title:"Stock Market Live News Updates: Sensex live today Nifty50 live today Nestle HCL Tech Larsen Toubro Tech Russia - CNBCTV18",
        author:"CNBCTV18.com",
        source:"CNBCTV18",
        category:"General",
        saved:false,
        description:"Stock Market Highlights: Indian equity benchmarks BSE Sensex and NSE Nifty50 continued to rise for a second straight day on Thursday led by gains across IT stocks and heavyweights Reliance Industries, Infosys and the HDFC twins. Broader marke",
        favourite:false,
    },
    {   
        id:1,
        url:"https://www.ndtv.com/india-news/sachin-pilot-meets-sonia-gandhi-over-his-future-role-in-congress-sources-2907424",
        img:"https://c.ndtvimg.com/2021-10/an9r19h4_sachin-pilot-pti-photo_625x300_06_October_21.jpg",
        time:"2022-04-21T12:03:22Z",
        title:"Sachin Pilot Meets Sonia Gandhi Over His Future Role In Congress: Sources - NDTV",
        author:null,
        source:"NDTV News",
        category:"General",
        saved:false,
        description:"Rajasthan Congress leader Sachin Pilot met with Sonia Gandhi today amid reports that he has expressed his fervent wish to become Chief Minister",
        favourite:false,
        
    },
    {
        id:2,
        url:"https://www.livemint.com/news/india/long-covid-more-severe-in-women-than-men-suggests-study-11650538683775.html",
        img:"https://images.livemint.com/img/2022/04/21/600x338/long_covid_symptoms_1650540839356_1650540839488.jpg",
        time:"2022-04-21T11:37:19Z",
        title:"Long Covid More Severe In Women Than Men, Suggests Study - Mint",
        author:"Livemint",
        source:"Livemint",
        category:"General",
        saved:false,
        description:"The study found that 91% of patients, who were followed up for five months on average, continued to experience Covid-19 symptoms. Breathlessness was the most common symptom of long Covid-19, followed by fatigue",
        favourite:false,
    },
    {
        id:3,
        url:"https://timesofindia.indiatimes.com/life-style/health-fitness/health-news/cdc-confirms-4-americans-got-coronavirus-from-mink-here-is-all-you-need-to-know-about-the-first-animal-to-human-transmission-of-covid-virus/photostory/90979229.cms",
        img:"https://static.toiimg.com/photo/90979239.cms",
        time:"2022-04-21T10:45:00Z",
        title:"CDC confirms 4 Americans got Coronavirus from Mink; here is all you need to know about the first animal-to-human transmission of COVID virus - Times of India",
        author:"TIMESOFINDIA.COM",
        source:"The Times of India",
        category:"General",
        saved:false,
        description:"The US health agency recently revealed that a variant of COVID witnessed majorly in mink in 2020 had infected at least four Americans.",
        favourite:false,
    },
    {   
        id:4,
        url:"https://www.news18.com/news/tech/apple-magsafe-battery-pack-will-now-charge-your-iphone-faster-heres-how-5026621.html",
        img:"https://images.news18.com/ibnlive/uploads/2022/04/apple-iphone-magsafe-battery-165053750816x9.jpg",
        time: "2022-04-21T10:41:56Z",
        title: "Apple MagSafe Battery Pack Will Now Charge Your iPhone Faster: Here’s How - News18",
        author: "Tech Desk",
        source:"News18",
        catefory:"General",
        saved:false,
        description: "Apple is offering its new firmware update for the MagSafe accessory that promises to give you faster charging for the compatible iPhone models.",
        favourite:false,
    },
    {
        id:5,
        url: "https://tech.hindustantimes.com/mobile/news/no-11-after-14-iphone-11-said-to-be-counting-its-last-days-71650537406297.html",
        img: "https://images.hindustantimes.com/tech/img/2022/04/21/1600x900/iPhone_11_1596385103788_1596385118692_1650537576825.JPG",
        time: "2022-04-21T10:40:12Z",
        title: "No 11 after 14! iPhone 11 said to be counting its LAST days - HT Tech",
        author: "HT Tech",
        source:"Hindustan Times",
        category:"General",
        saved:false,
        description: "iPhone 11 now said to be discontinued after iPhone 14 launch later in 2022. Here are all the details.",
        favourite:false,
    },
    {
        id:6,
        url: "https://www.manutd.com/en/news/detail/erik-ten-hag-appointed-as-man-utd-manager-official-statement",
        img: "https://assets.manutd.com/AssetPicker/images/0/0/16/141/1084869/NMS_Article_Header_copy1650534418325_large.jpg",
        time: "2022-04-21T10:10:00Z",
        title: "Official statement: Erik ten Hag - Man Utd",
        author: "Communications Department",
        source: "Manchester United",
        category:"General",
        saved:false,
        description: "Manchester United is delighted to announce the appointment of Erik ten Hag as Men's First Team Manager, subject to work visa requirements.",
        favourite:false
    },
    {
        id: 7,
        url: "https://indianexpress.com/article/india/kishor-wants-to-join-cong-preconditions-induction-will-help-party-congress-gen-secy-tariq-anwar-7880283/",
        img: "https://images.indianexpress.com/2018/09/tariq-anwar.jpg",
        time: "2022-04-21T10:03:18Z",
        title: "Kishor wants to join Cong without preconditions, his induction will help party: Gen secy Tariq Anwar - The Indian Express",
        author: "PTI",
        source: "The Indian Express",
        category:"General",
        saved:false,
        description: "Discussing the party's fortunes, Anwar said the Congress would be the natural leader of an anti-BJP front for the 2024 general elections as no other party has its pan-India appeal or its presence.",
        favourite: false
    },
    {
        id: 8,
        url: "https://www.ndtv.com/india-news/dont-lecture-judiciary-supreme-court-to-centre-over-abu-salem-plea-2906903",
        img: "https://i.ndtvimg.com/i/2017-06/abu-salem_650x400_71497587927.jpg",
        time: "2022-04-21T10:00:24Z",
        title: "\"Don't Lecture Judiciary\": Supreme Court To Centre Over Abu Salem Plea - NDTV",
        author: null,
        source: "NDTV News",
        category:"General",
        saved:false,
        description:  "On gangster Abu Salem's petition against his jail sentence, the Supreme Court today used stern words while rejecting the Union Home Ministry's stance that the plea is premature.",
        favourite: false
    },
    {
        id: 9,
        url: "https://www.indiatoday.in/technology/news/story/oneplus-nord-ce-2-lite-5g-buds-launch-india-april-28-1940164-2022-04-21",
        img: "https://akm-img-a-in.tosshub.com/indiatoday/images/story/202204/OnePlus_Nord_CE_2_Lite_5G_and_-647x363.jpeg?EgEFMdJRwkxcWtYg2J4692ceDaR3v3g1",
        time: "2022-04-21T09:42:11Z",
        title: "Nord CE 2 Lite 5G and Nord Buds arriving on April 28 in India as OnePlus goes big on brand Nord - India Today",
        author: null,
        source: "India Today",
        category:"General",
        saved:false,
        description: "Brand Nord from the house of OnePlus is growing. Two more products -- OnePlus Nord CE 2 Lite 5G and OnePlus Nord Buds -- will be launching in India on April 28.",
        favourite: false
    },
    {
        id:10,
        url: "https://www.hindustantimes.com/entertainment/bollywood/priyanka-chopra-honoured-mom-madhu-chopra-mom-in-law-denise-jonas-with-daughter-malti-s-name-here-s-how-101650530353702.html",
        img: "https://images.hindustantimes.com/img/2022/04/21/1600x900/Priyanka_Chopra_1650530350307_1650530350460.jpg",
        time : "2022-04-21T09:28:15Z",
        title: "Priyanka Chopra honoured mom, mom-in-law with daughter Malti's name. Here's how - Hindustan Times",
        author : "HT Entertainment Desk",
        source : "Hindustan Times",
        category: "General",
        saved:false,
        description : "The name of Priyanka Chopra's daughter was revealed on Thursday after the media got their hands on the child's birth certificate.",
        favourite: false
    },
    {
        id:11,
        url : "https://www.livelaw.in/top-stories/you-require-bulldozers-to-remove-stalls-chairs-supreme-court-asks-ndmc-on-jahangirpuri-demolitions-197162",
        img : "https://www.livelaw.in/h-upload/2022/04/20/415272-jahangirpuri-demolitions-sc.jpg",
        time : "2022-04-21T09:14:19Z",
        title : "You Require Bulldozers To Remove Stalls & Chairs?: Supreme Court Asks NDMC On Jahangirpuri Demolitions - Live Law - Indian Legal News",
        author : "Srishti Ojha",
        source: "Livelaw.in",
        category: "General",
        saved:false,
        description: "To remove stalls, chairs, bench, boxes, you require a bulldozer?, the Supreme Court on Thursday...",
        favourite : false
    },
    {
        id:12,
        url: "https://www.ndtv.com/world-news/watch-nasas-perseverance-rover-captures-stunning-video-of-solar-eclipse-on-mars-2906661",
        img : "https://c.ndtvimg.com/2022-04/6mucfk4g_mars-650_625x300_21_April_22.jpg",
        time : "2022-04-21T09:02:03Z",
        title: "Watch: NASA's Perseverance Rover Captures Stunning Video of Solar Eclipse On Mars - NDTV",
        author: null,
        source:"NDTV News",
        category: "General",
        saved:false,
        description : "NASA's Perseverance Mars rover has captured a mesmerising video of a solar eclipse on the Red Planet. The camera onboard the SUV-sized rover captured the footage of Phobos, Mars potato-shaped moon, crossing the face of the Sun.",
        favourite: false,
    },
    {
        id:13,
        url: "https://www.indiatoday.in/coronavirus-outbreak/story/delhi-covid-cases-omicron-sub-types-1940147-2022-04-21",
        img : "https://akm-img-a-in.tosshub.com/indiatoday/images/story/202204/Coronaviruss-647x363.jpeg?tghPHp5D35v8aprchguXYILJcwaYeIx5",
        time : "2022-04-21T09:02:00Z",
        title : "Omicron and its 9 sub-types driving up Delhi Covid cases, say govt sources - India Today",
        author : null,
        source: "India Today",
        category: "General",
        saved:false,
        description : "Government sources attributed the rise in the number of Covid cases in Delhi to the Omicron variant of coronavirus and its sub-types.",
        favourite: false,
    },
    {
        id: 14,
        url: "https://www.iplt20.com/news/3778/matheesha-pathirana-joins-chennai-super-kings-as-a-replacement-for-adam-milne",
        img : "https://assets.iplt20.com/bcci/articles/1650530256__AI_8942%20%281%29.jpg",
        time : "2022-04-21T08:46:13Z",
        title : "Matheesha Pathirana joins Chennai Super Kings as a replacement for Adam Milne - IPLT20.com",
        author : null,
        source: "Iplt20.com",
        category: "General",
        saved:false,
        description: "Matheesha Pathirana joins Chennai Super Kings as a replacement for Adam Milne",
        favourite : false
    },
    {
        id: 15,
        url: "https://www.moneycontrol.com/news/india/boris-johnson-india-visit-live-updates-india-visit-will-deepen-strategic-ties-says-british-pm-boris-johnson-8387411.html",
        img : "https://images.moneycontrol.com/static-mcnews/2022/04/1-boris-johnson-sabarmati-visit-770x433.jpg",
        time : "2022-04-21T08:38:00Z",
        title: "Boris Johnson India Visit LIVE Updates: UK PM meets Gautam Adani in Ahemdabad - Moneycontrol",
        author: "Moneycontrol News",
        source: "Moneycontrol",
        category: "General",
        saved:false,
        description: "Boris Johnson's India Visit Live Updates: The British Prime Minister said that his long-delayed visit to India will deepen the strategic trade, defence, and people-to-people ties between the two countries.",
        favourite : false
    },
    {
        id: 16,
        url: "https://www.ndtv.com/india-news/eight-hour-blackouts-slam-india-after-hottest-march-since-1901-2906423",
        img : "https://c.ndtvimg.com/2022-04/4adlt3r4_power-grid-generic-reuters_625x300_15_April_22.jpg",
        time : "2022-04-21T08:11:16Z",
        title : "8-Hour Blackouts Hit India, Point To \"Looming Power Crisis\" - NDTV",
        author : null,
        source: "NDTV News",
        category: "General",
        saved:false,
        description : "An already sweltering summer and acute coal shortages are triggering blackouts across parts of India, raising fears of a new power crisis that could roil Asia's third-biggest economy.",
        favourite : false
    },
    {
        id: 17,
        url: "https://www.ndtv.com/world-news/vladimir-putin-hails-successful-liberation-of-mariupol-news-agency-afp-2906410",
        img : "https://c.ndtvimg.com/2022-04/s0n78k4o_mariupol_625x300_21_April_22.jpg",
        time : "2022-04-21T08:10:38Z",
        title : "\"Mariupol Has Been Liberated\": Putin Says \"Success\" For Russian Forces - NDTV",
        author: null,
        source : "NDTV News",
        category: "General",
        saved:false,
        description : "President Vladimir Putin on Thursday hailed Russia's \"liberation\" of Mariupol after Defence Minister Sergei Shoigu told him Moscow controlled the Ukrainian port city apart from the giant Azovstal steel plant.",
        favourite : false
    },
    {
        id: 18,
        url: "https://indianexpress.com/article/explained/explained-russia-ukraine-war-nuclear-missile-sarmat-7880021/",
        img: "https://images.indianexpress.com/2022/04/ICBM.jpg",
        time : "2022-04-21T08:05:23Z",
        title: "Explained: What is Russia’s new nuclear missile Sarmat, capable of striking ‘anywhere in the world’? - The Indian Express",
        author : "Man Aman Singh Chhina",
        source: "The Indian Express",
        category: "General",
        saved:false,
        description: "The RS-28 Sarmat, also called Satan-II, is reported to be able to carry ten or more warheads and decoys, and has the capability of firing over either of the earth’s poles with a range of 11,000 to 18,000 km.",
        favourite : false
    },
    {
        id : 19,
        url: "https://theprint.in/science/on-jupiters-icy-moon-europa-shallow-pools-of-underground-salt-water-offer-promise-of-life/923670/",
        img : "https://static.theprint.in/wp-content/uploads/2022/04/Europa_moon.jpg",
        time : "2022-04-21T07:23:12Z",
        title : "On Jupiter’s icy moon Europa, shallow pools of underground salt water offer promise of life - ThePrint",
        author : null,
        source: "ThePrint",
        category: "General",
        saved:false,
        description: "While shallow water processes have been suspected on Europa, if findings of study are confirmed, it could mean they play bigger-than-expected role in shaping its surface features.",
        favourite : false
    },
    {
        id : 20,
        url : "https://www.koimoi.com/box-office/jersey-box-office-day-1-advance-booking-a-day-before-release-shahid-kapoors-film-is-entirely-word-of-mouth-dependent-as-theres-hardly-any-buzz/",
        img : "https://static-koimoi.akamaized.net/wp-content/new-galleries/2022/04/jersey-box-office-day-1-advance-booking-a-day-before-release-001.jpg",
        time : "2022-04-21T06:53:26Z",
        title : "Jersey Box Office Day 1 Advance Booking (A Day Before Release): Shahid Kapoor’s Film Is Entirely Word-Of-Mouth Dependent As There’s Hardly Any Buzz - Koimoi",
        author : "Koimoi.com Team",
        source:"Koimoi",
        category: "General",
        saved:false,
        description: "Finally, Shahid Kapoor fans have got a chance to cheer as his Jersey to hit theatres tomorrow. Here's its advance booking report.",
        favourite : false
    },
    {
        id: 21,
        url: "https://www.hindustantimes.com/india-news/national-database-on-internal-security-in-works-amit-shah-101650523423101.html",
        img : "https://images.hindustantimes.com/img/2022/04/21/1600x900/0807e2d0-c13d-11ec-bc83-62b7767857b3_1650523421994.jpg",
        time : "2022-04-21T06:43:42Z",
        title : "National database on internal security in works: Amit Shah - Hindustan Times",
        author : "Neeraj Chauhan",
        source: "Hindustan Times",
        category: "General",
        saved:false,
        description: "The Union home minister said the database will go a long way in helping investigations and ensuring convictions of terror accused | Latest News India",
        favourite : false
    },
    {
        id : 22,
        url: "https://www.hindustantimes.com/india-news/top-let-commander-yousuf-kantroo-killed-in-encounter-in-kashmir-s-baramulla-101650520152247.html",
        img : "https://images.hindustantimes.com/img/2022/04/21/1600x900/20891acc-bf58-11ec-bc83-62b7767857b3_1650314712075_1650521832815.jpg",
        time : "2022-04-21T06:18:26Z",
        title: "Top LeT commander Yousuf Kantroo among 2 terrorists killed in J&K's Baramulla - Hindustan Times",
        author: "HT News Desk",
        source: "Hindustan Times",
        category: "General",
        saved:false,
        description: "Yousuf Kantroo, a top LeT commander who was on the hit list of Indian Army, was involved in several killings of civilians and security forces personnel. | Latest News India",
        favourite: false
    },
    {
        id : 23,
        url: "https://citytoday.news/liver-cancer-is-increasing-because-of-unhealthy-lifestyle/",
        img: null,
        time : "2022-04-21T05:41:53Z",
        title: "Liver cancer is increasing because of unhealthy lifestyle – Mysuru Today - citytoday",
        author: "Murali",
        source: "Citytoday.news",
        category: "General",
        saved:false,
        description: "Prime News, National, Karnataka, Health, Disease, Mysuru, April 21:- Liver cancer is rising because of an unhealthy lifestyle, said Dr M S Vishveshwara, Chief Radiation Oncologist and Medical Superint",
        favourite : false
    },
    {
        id: 24,
        url: "https://www.bollywoodlife.com/photos/akshay-kumar-rashmika-mandanna-ranveer-singh-and-more-stars-who-were-massively-trolled-for-controversial-ads-bollywood-galleries-entertainment-news-2054655/",
        img: "https://st1.bollywoodlife.com/wp-content/uploads/2022/04/Akshay-15-600x315.png",
        time : "2022-04-21T05:24:49Z",
        title : "Akshay Kumar, Rashmika Mandanna, Ranveer Singh and more stars who were massively trolled for controversial ads - Bollywood Life",
        author: "Nikita Thakkar",
        source : "Bollywood Life",
        category: "General",
        saved: false,
        description: "Akshay Kumar had to issue an apology after he received severe backlash over his latest advertisement. Here's a list of stars who have been trolled for similar reasons.",
        favourite : false
    },
    {
        id : 25,
        url: "https://www.news18.com/news/business/hcl-tech-q4-results-today-profit-attrition-5-things-to-watch-out-for-5023555.html",
        img : "https://images.news18.com/ibnlive/uploads/2022/01/hcl-164198628716x9.jpg",
        time : "2022-04-21T05:20:42Z",
        title: "HCL Tech Q4 Results Today: Profit, Attrition; 5 Things To Watch Out For - News18",
        author: "Business Desk",
        source:"News18",
        category : "General",
        saved: false,
        description: "HCL Tech Q4 Results: Net profit, revenue growth, outlook, large deal wins and attrition rate are the key 5 factors to watch out for",
        favourite : false
    },
    {
        id : 26,
        url: "https://tech.hindustantimes.com/tech/news/do-not-miss-april-23-29-sunrise-rare-celestial-view-of-4-planets-coming-moon-and-mercury-to-join-later-71650515334974.html",
        img : "https://images.hindustantimes.com/tech/img/2022/04/21/1600x900/Space_1650515656075_1650515661318.jpg",
        time : "2022-04-21T04:32:00Z",
        title: "Do NOT miss April 23-29 sunrise! RARE celestial view of 4 planets coming; MOON and Mercury to join later - HT Tech",
        
        "source": {
            "id": null,
            "name": "Hindustan Times"
        },
        "author": "HT Tech",
        "description": "The four planets of our solar system will line up as a quartet on the dawn hours of April 29. NASA says you don’t need telescope to see it.",
        "content": "If you love stargazing, then prepare to give up your sleep a little and wake up early on April 29. We know it sounds cruel for all the sleep lovers but the view will be worth it. Because NASA says th… [+2068 chars]"
    },
    {
        "source": {
            "id": "the-times-of-india",
            "name": "The Times of India"
        },
        "author": "Bloomberg",
        "title": "Covid-19: Elderly Shanghai woman's quarantine ordeal sparks outrage - Times of India",
        "description": "China News: About two thirds of Shanghai’s 25 million residents remain under a lockdown that started three weeks ago -- and nerves have been frayed by the experie",
        "url": "https://timesofindia.indiatimes.com/world/china/covid-19-elderly-shanghai-womans-quarantine-ordeal-sparks-outrage/articleshow/90971504.cms",
        "urlToImage": "https://static.toiimg.com/thumb/msid-90971508,width-1070,height-580,imgsize-186272,resizemode-75,overlay-toi_sw,pt-32,y_pad-40/photo.jpg",
        "publishedAt": "2022-04-21T04:31:00Z",
        "content": "Covid-19: Elderly Shanghai woman's quarantine ordeal sparks outrage"
    },
    {
        "source": {
            "id": null,
            "name": "Hindustan Times"
        },
        "author": "HT Sports Desk",
        "title": "DC vs PBKS Highlights, IPL: Delhi Capitals beat Punjab Kings by nine wickets - Hindustan Times",
        "description": "IPL 2022 Highlights, Delhi Capitals vs Punjab Kings: David Warner and Sarfaraz Khan guided Delhi home with 57 balls to spare. Follow the Highlights of DC vs PBKS:",
        "url": "https://www.hindustantimes.com/cricket/dc-vs-pbks-live-score-ipl-2022-delhi-capitals-vs-punjab-kings-t20-match-32-latest-updates-full-scorecard-and-cricket-news-101650448827402.html",
        "urlToImage": "https://images.hindustantimes.com/img/2022/04/20/1600x900/rabada_1650471180984_1650471192179.jpg",
        "publishedAt": "2022-04-21T02:48:29Z",
        "content": "Punjab Kings: Mayank Agarwal(c), Shikhar Dhawan, Jonny Bairstow, Liam Livingstone, Jitesh Sharma(w), Shahrukh Khan, Kagiso Rabada, Nathan Ellis, Rahul Chahar, Vaibhav Arora, Arshdeep Singh\r\nDelhi Cap… [+171 chars]"
    },
    {
        "source": {
            "id": null,
            "name": "NDTV News"
        },
        "author": null,
        "title": "Boris Johnson Faces Calls To Apologise For Colonial-Era Massacre In India - NDTV",
        "description": "British Prime Minister Boris Johnson faces calls to apologise for a colonial-era massacre when he visits Gujarat today, 100 years after as many as 1,200 people were killed protesting against imperial rule.",
        "url": "https://www.ndtv.com/india-news/pal-dadhvav-massacre-boris-johnson-faces-calls-to-apologise-for-colonial-era-massacre-in-india-2905819",
        "urlToImage": "https://c.ndtvimg.com/2022-04/g8es6fag_boris-johnson-reuters_625x300_21_April_22.jpg",
        "publishedAt": "2022-04-21T02:28:02Z",
        "content": "British Prime Minister Boris Johnson will land in India today on a two-day visit\r\nNew Delhi: British Prime Minister Boris Johnson faces calls to apologise for a colonial-era massacre when he visits G… [+3288 chars]"
    },
    {
        "source": {
            "id": null,
            "name": "Hindustan Times"
        },
        "author": "HT News Desk",
        "title": "India’s high growth rate 'positive news' for world: IMF - Hindustan Times",
        "description": "Kristalina Georgieva, managing director of the international financial institution, was speaking on the sidelines of the annual spring meeting of the IMF and the World Bank in Washington.",
        "url": "https://www.hindustantimes.com/business/indias-high-growth-rate-positive-news-for-world-imf-101650506302217.html",
        "urlToImage": "https://images.hindustantimes.com/img/2022/04/21/1600x900/file-photo-international-monetary-fund-logo-seen_e1b65fb6-1414-11eb-b504-c4c734a23405_1650508957496.jpg",
        "publishedAt": "2022-04-21T02:02:42Z",
        "content": "International Monetary Fund (IMF) chief Kristalina Georgieva on Wednesday lauded India's high growth rate, as projected in the latest World Economic Outlook, saying that it is positive news for the w… [+1728 chars]"
    },
    {
        "source": {
            "id": null,
            "name": "Cricketaddictor.com"
        },
        "author": "More by Vicky Singh",
        "title": "Mumbai Indians vs Chennai Super kings Dream11 Prediction, Fantasy Cricket Tips, Dream11 Team, Playing XI, Pitch Report, Injury Update- Tata IPL 2022 - Cricket Addictor",
        "description": "Mumbai Indians vs Chennai Super kings Dream11 Prediction, Fantasy Cricket Tips, Dream11 Team, Playing XI, Pitch Report, Injury Update- Tata IPL 2022",
        "url": "https://cricketaddictor.com/fantasy-cricket/mumbai-indians-vs-chennai-super-kings-dream11-prediction-fantasy-cricket-tips-dream11-team-playing-xi-pitch-report-injury-update-tata-ipl-2022/",
        "urlToImage": "https://cricketaddictor.com/wp-content/uploads/2022/04/2-2-6.png",
        "publishedAt": "2022-04-21T01:46:57Z",
        "content": "Mumbai Indians vs Chennai Super kings Dream11 Prediction, Fantasy Cricket Tips, Dream11 Team, Playing XI, Pitch Report, Injury Update of Tata IPL 2022 match between Mumbai Indians and Chennai Super K… [+6057 chars]"
    },
    {
        "source": {
            "id": null,
            "name": "The Indian Express"
        },
        "author": "Pranav Mukul",
        "title": "Attrition high, so Infosys & TCS invoke job clause to retain talent - The Indian Express",
        "description": "The non-compete clause under contention says that after resigning, an Infosys employee cannot work, for a period of six months, with one of the named rival companies on a client he or she would have serviced in the preceding 12 months before quitting.",
        "url": "https://indianexpress.com/article/business/companies/attrition-high-so-infosys-tcs-invoke-job-clause-to-retain-talent-7879293/",
        "urlToImage": "https://images.indianexpress.com/2022/04/INFOSYS-REUTERS-1200-1-1.jpg",
        "publishedAt": "2022-04-21T01:18:38Z",
        "content": "An overheated job market in the software and BPO space has triggered a surge in attrition rates at TCS and Infosys, the top two IT companies in the country by revenue, prompting tech companies to fal… [+3425 chars]"
    },
    {
        "source": {
            "id": null,
            "name": "PINKVILLA"
        },
        "author": "Pinkvilla Desk",
        "title": "Here's why Johnny Depp's daughter Lily-Rose skipped his wedding with Amber Heard - PINKVILLA",
        "description": "Johnny Depp testified about his and Amber Heard's wedding day, including why his daughter was not in attendance.",
        "url": "https://www.pinkvilla.com/entertainment/hollywood/heres-why-johnny-depps-daughter-lily-rose-skipped-his-wedding-amber-heard-1073054",
        "urlToImage": "https://www.pinkvilla.com/files/styles/fbimagesection/public/johnny_lily_depp_social.jpg?itok=9OJH0l0B",
        "publishedAt": "2022-04-20T22:30:37Z",
        "content": "Johnny Depp, 58, has revealed surprising information about his wedding to Amber Heard and the impact it had on his daughter Lily-Rose Depp. On Wednesday, the actor testified in his defamation trial a… [+1390 chars]"
    },
    {
        "source": {
            "id": null,
            "name": "Road to VR"
        },
        "author": "Ben Lang",
        "title": "‘Among Us VR’ Gets First Gameplay Trailer, Coming to Quest & PC VR This Holiday, PSVR 2 Eventually - Road to VR",
        "description": "Party game sensation Among Us has been known to be getting a full-blown VR version since late last year but now we’re getting our first good look at some gameplay. Developer Schell Games has also floated a ‘holiday 2022’ release date for the game on Quest and…",
        "url": "https://www.roadtovr.com/among-us-vr-gameplay-trailer-quest-2-pc-vr-psvr-2-release-date/",
        "urlToImage": "https://roadtovrlive-5ea0.kxcdn.com/wp-content/uploads/2021/12/among-us-vr-remake-1.png",
        "publishedAt": "2022-04-20T17:07:46Z",
        "content": "Party game sensation Among Us has been known to be getting a full-blown VR version since late last year but now we’re getting our first good look at some gameplay. Developer Schell Games has also flo… [+1979 chars]"
    }
]

export default data;

